name: 编译3

on:
  #schedule:
    #- cron: '0 3,20 * * *'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  TZ: Asia/Shanghai
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armv7-unknown-linux-gnueabihf
    steps:
     
      - uses: actions/checkout@v2
      - 
        name: 编译
        run: |
          mkdir -p /opt/musl_gcc 
          wget -c https://github.com/lmq8267/vnt-cli/releases/download/Armada370-ToolChain/armada370-gcc493_glibc220_hard-GPL.txz -P /opt/musl_gcc/
          tar -Jxvf /opt/musl_gcc/armada370-gcc493_glibc220_hard-GPL.txz -C /opt/musl_gcc/
          #sudo ln -s $(pwd)/musl_gcc/mipsel-linux-musl-cross/bin/*gcc /usr/bin/
          #sudo apt-get install -qq gcc-arm-linux-gnueabihf
          rustup target add armv7-unknown-linux-gnueabihf
          export PATH=$PATH:/opt/musl_gcc/arm-unknown-linux-gnueabi/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/musl_gcc/arm-unknown-linux-gnueabi/lib/gcc/arm-unknown-linux-gnueabi/4.9.3
          arm-unknown-linux-gnueabi-gcc --version
          cat >>~/.cargo/config <<EOF
          [target.armv7-unknown-linux-gnueabihf]
          linker = "arm-unknown-linux-gnueabi-gcc"
          rustflags = ["-C", "target-feature=+crt-static"]
          EOF
          cd /opt
          git clone https://github.com/lbl8603/vnt.git /opt/vnt
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          tar -xvf /opt/st/upx-4.1.0-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-4.1.0-amd64_linux/upx
          #chmod 777 /opt/st/strip
          #mkdir -p /opt/vnt-mipsel
          cd /opt/vnt
          cargo build --package vnt-cli --target=armv7-unknown-linux-gnueabihf --release --features openssl-vendored
          mv /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli_370_ssl_release
          /opt/musl_gcc/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-strip /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli_370_ssl_release
          file /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli_370_ssl_release
          cp /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli_370_ssl_release /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli_370_ssl_release_upx
          /opt/upx-4.1.0-amd64_linux/upx /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli_370_ssl_release_upx
          #/opt/musl_gcc/lede-sdk-17.01.0-mvebu_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.4.0_musl-1.1.16_eabi/bin/arm-openwrt-linux-strip vnt-cli
          #/opt/upx-4.1.0-amd64_linux/upx vnt-cli
          #mv vnt-cli vnt-cli_370
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - 
        name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           ### *
          tag_name: 370arm7
          files: |
              /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli_370_ssl_release
              /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli_370_ssl_release_upx
