name: 编译buildroot

on:
  #schedule:
    #- cron: '0 3,20 * * *'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  CONFIG_FILE: .config
  TZ: Asia/Shanghai
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 构建gcc
        run: |
          git clone https://github.com/buildroot/buildroot.git /opt/buildroot
          [ -e $CONFIG_FILE ] && cp -rf $CONFIG_FILE /opt/buildroot/.config
          sudo chmod a+w /opt/buildroot
          echo -e "使用$(nproc)线程构建"
          cd /opt/buildroot
          make menuconfig
          make -j$(nproc)
          cd /opt/buildroot/output/host/bin
          mipsel-linux-gcc --version
      
