name: 编译

on:
  #schedule:
    #- cron: '0 3,20 * * *'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  TZ: Asia/Shanghai
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: 检查更新
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/lbl8603/vnt/releases/latest | jq -r '.tag_name'`
          #vntsv=`curl https://api.github.com/repos/lbl8603/vnts/releases/latest | grep 'tag_name' | cut -d\" -f4`
          cver=`curl https://api.github.com/repos/lmq8267/vnt-cl/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry-mipsel-unknown-linux-musl
      - name: List
        run: find ./
      - 
        name: 编译
        run: |
          mkdir -p ./musl_gcc 
          wget -c https://musl.cc/mipsel-linux-musl-cross.tgz -P ./musl_gcc/
          tar zxf ./musl_gcc/mipsel-linux-musl-cross.tgz -C ./musl_gcc/
          sudo ln -s $(pwd)/musl_gcc/mipsel-linux-musl-cross/bin/*gcc /usr/bin/
          rustup target add mipsel-unknown-linux-musl
          cat >>~/.cargo/config <<EOF
          [target.mipsel-unknown-linux-musl]
          linker = "mipsel-linux-musl-gcc"
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          EOF
          git clone https://github.com/lbl8603/vnt.git /opt/vnt
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          chmod 777 /opt/st/strip
          mkdir -p /opt/vnt-mipsel
          cd /opt/vnt
          #sed -i 's|0.9.25|0.8.26|g' ./vnt-cli/Cargo.toml
          echo 编译无任何加密版
          cargo build --package vnt-cli --target=mipsel-unknown-linux-musl --release --no-default-features
          cp -f /opt/vnt/target/mipsel-unknown-linux-musl/release/vnt-cli /opt/vnt-mipsel/vnt-cli_lite
          cargo clean
          echo 编译openssl版
          cargo build --package vnt-cli --target=mipsel-unknown-linux-musl --release --no-default-features --features openssl-vendored,aes_ecb,server_encrypt,aes_gcm
          cp -f /opt/vnt/target/mipsel-unknown-linux-musl/release/vnt-cli /opt/vnt-mipsel/vnt-cli_openssl
          cargo clean
          echo 编译默认加密版
          cargo build --package vnt-cli --target=mipsel-unknown-linux-musl --release --features default
          cp -f /opt/vnt/target/mipsel-unknown-linux-musl/release/vnt-cli /opt/vnt-mipsel/vnt-cli_default
          cargo clean
          echo 编译全加密版
          cargo build --package vnt-cli --target=mipsel-unknown-linux-musl --release --features openssl-vendored
          cp -rf /opt/vnt/target/mipsel-unknown-linux-musl/release/vnt-cli /opt/vnt-mipsel/vnt-cli_full
          cd /opt/vnt-mipsel
          /opt/st/strip /opt/vnt-mipsel/vnt-cli_lite
          /opt/upx-3.95-amd64_linux/upx --lzma --best vnt-cli_lite
          /opt/st/strip /opt/vnt-mipsel/vnt-cli_full
          /opt/upx-3.95-amd64_linux/upx --lzma --best vnt-cli_full
          /opt/st/strip /opt/vnt-mipsel/vnt-cli_openssl
          /opt/upx-3.95-amd64_linux/upx --lzma --best vnt-cli_openssl
          /opt/st/strip /opt/vnt-mipsel/vnt-cli_default
          /opt/upx-3.95-amd64_linux/upx --lzma --best vnt-cli_default
          echo $(md5sum vnt-cli_lite | awk '{print $1;}') >lite_MD5.txt
          echo $(md5sum vnt-cli_full | awk '{print $1;}') >full_MD5.txt
          echo $(md5sum vnt-cli_openssl | awk '{print $1;}') >openssl_MD5.txt
          echo $(md5sum vnt-cli_default | awk '{print $1;}') >default_MD5.txt
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - 
        name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           测试
          tag_name: ${{ needs.check.outputs.ver }}
          files: |
              /opt/vnt-mipsel/*
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
