name: 编译mipsel版vnt-cli

on:
  #schedule:
    #- cron: '0 3,20 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: 检查更新
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/lbl8603/vnt/releases/latest | jq -r '.tag_name'`
          #vntsv=`curl https://api.github.com/repos/lbl8603/vnts/releases/latest | grep 'tag_name' | cut -d\" -f4`
          cver=`curl https://api.github.com/repos/lmq8267/vnt-cli/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry-mipsel-unknown-linux-musl
      - name: List
        run: find ./
      - 
        name: 编译
        run: |
          mkdir -p ./musl_gcc 
          wget -c https://musl.cc/mipsel-linux-musl-cross.tgz -P ./musl_gcc/
          tar zxf ./musl_gcc/mipsel-linux-musl-cross.tgz -C ./musl_gcc/
          sudo ln -s $(pwd)/musl_gcc/mipsel-linux-musl-cross/bin/*gcc /usr/bin/
          rustup target add mipsel-unknown-linux-musl
          cat >>~/.cargo/config <<EOF
          [target.mipsel-unknown-linux-musl]
          linker = "mipsel-linux-musl-gcc"
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols","--cfg","aes_armv8"]
          EOF
          git clone https://github.com/lmq8267/vnt-cli.git /opt/vnt
          #git clone https://github.com/lbl8603/vnt -b ${{ needs.check.outputs.ver }} /opt/vnt
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          chmod 777 /opt/st/strip
          mkdir -p /opt/vnt-mipsel
          cd /opt/vnt
          cargo build --package vnt-cli --target=mipsel-unknown-linux-musl --release --features normal
          cp -f /opt/vnt/target/mipsel-unknown-linux-musl/release/vnt-cli /opt/vnt-mipsel/vnt-cli
          #cd /opt/vnts
          #cargo build --release --verbose --target mipsel-unknown-linux-musl --features normal
          #mv ./target/$TARGET/release/vnts mkdir -p /opt/vnt-mipsel/vnts
           cd /opt/vnt-mipsel
          /opt/st/strip /opt/vnt-mipsel/vnt-cli
          #/opt/st/strip /opt/vnt-mipsel/vnts
          /opt/upx-3.95-amd64_linux/upx --lzma --best vnt-cli
          #/opt/upx-3.95-amd64_linux/upx --lzma --best vnts
          echo $(md5sum vnt-cli | awk '{print $1;}') >MD5.txt
          #echo $(md5sum vnts | awk '{print $1;}') >vnts.txt
      - 
        name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           这个是使用重定向域名的vnt-cli 
           特别修改版
           正常使用的不要下载这个
           前往vnt那个仓库下载
          tag_name: ${{ needs.check.outputs.ver }}
          files: |
              /opt/vnt-mipsel/vnt-cli
              /opt/vnt-mipsel/MD5.txt
              #/opt/vnt-mipsel/vnts
              #/opt/vnt-mipsel/vnts.txt
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
