name: 编译arm

on:
  #schedule:
    #- cron: '0 3,20 * * *'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  TZ: Asia/Shanghai
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armv7-unknown-linux-musleabi
    steps:
     
      - uses: actions/checkout@v2
      - 
        name: 编译
        run: |
          mkdir -p /opt/musl_gcc 
          wget -c https://archive.openwrt.org/releases/17.01.0/targets/mvebu/generic/lede-sdk-17.01.0-mvebu_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz -P /opt/musl_gcc/
          tar -xvf /opt/musl_gcc/lede-sdk-17.01.0-mvebu_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz -C /opt/musl_gcc/
          #sudo ln -s $(pwd)/musl_gcc/mipsel-linux-musl-cross/bin/*gcc /usr/bin/
          rustup target add armv7-unknown-linux-musleabi
          export PATH=$PATH:/opt/musl_gcc/lede-sdk-17.01.0-mvebu_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.4.0_musl-1.1.16_eabi/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/musl_gcc/lede-sdk-17.01.0-mvebu_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.4.0_musl-1.1.16_eabi/lib
          arm-openwrt-linux-gcc --version
          cat >>~/.cargo/config <<EOF
          [target.armv7-unknown-linux-musleabi]
          linker = "arm-openwrt-linux-gcc"
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          EOF
          git clone https://github.com/lbl8603/vnt.git /opt/vnt
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          tar -xvf /opt/st/upx-4.1.0-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-4.1.0-amd64_linux/upx
          chmod 777 /opt/st/strip
          mkdir -p /opt/vnt-mipsel
          cd /opt/vnt
          cross build --package vnt-cli --target=armv7-unknown-linux-musleabi --release --features default
          cd /opt/vnt/target/armv7-unknown-linux-musleabi/release
          file vnt-cli
          /opt/musl_gcc/lede-sdk-17.01.0-mvebu_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.4.0_musl-1.1.16_eabi/bin/arm-openwrt-linux-strip vnt-cli
          /opt/upx-4.1.0-amd64_linux/upx vnt-cli
          mv vnt-cli vnt-cli_armv7
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - 
        name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           ### *
          tag_name: armtest
          files: |
              /opt/vnt/target/armv7-unknown-linux-musleabi/release/vnt-cli_armv7
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
